// Generated by CoffeeScript 1.9.1
(function() {
  define(function(require) {
    var Pattern;
    Pattern = require("SQL_Engine/SQL_ParserPattern");
    return describe("ParserPattern", function() {
      it("should be defined", function() {
        return expect(Pattern).toBeDefined();
      });
      it('should be accept exec function', function() {
        var execFn, txt;
        execFn = jasmine.createSpy();
        txt = new Pattern(execFn);
        txt.exec('hello', 0);
        return expect(execFn).toHaveBeenCalledWith('hello', 0);
      });
      it('should be able to transform result', function() {
        var txt;
        txt = new Pattern(function(str, pos) {
          return {
            res: str,
            end: 2
          };
        }).then(function(res) {
          return "transformed" + res;
        });
        return expect(txt.exec('hello', 0)).toEqual({
          res: 'transformedhello',
          end: 2
        });
      });
      return it('return nothing if pattern does not match', function() {
        var txt;
        txt = new Pattern(function(str, pos) {}).then(function(res) {
          return "it's not going to be returned";
        });
        return expect(txt.exec('ffff', 0)).toBeUndefined();
      });
    });
  });

}).call(this);

//# sourceMappingURL=SQL_ParserPatternSpec.js.map
